name: "Test actions-warp"

on:
    workflow_dispatch:
    release:
        types: [created]
        tags:
            - "v*"


jobs:
    warped-connection:
        runs-on: ubuntu-latest
        steps:
            - uses: sebst/actions-warp@v1
              with:
                tos: 'YES'
            - name: Check WARP connection
              run: |
                curl -s https://www.cloudflare.com/cdn-cgi/trace | grep "warp=on"
